on:
  push

name: ci

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: docker-practice/actions-setup-docker@master
      - uses: actions/checkout@v3
      - run: |
            set -x

            docker version

            ls -lah
            cd development
            docker-compose up -d
            sleep 5
            docker-compose up -d
      - run: |
            set -x
            cd development
            sleep 200
            docker-compose exec -T rt2nb_runner /opt/repo/development/rt2nb_runner_run_migration.sh
      
